<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'qtk_local_qtk_codigo_cliente_1' => 
  array (
    'id' => '1b1d9518-83cb-c233-d35f-5d1eb55664f0',
    'relationship_name' => 'qtk_local_qtk_codigo_cliente_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_codigo_cliente_1_c',
    'join_key_lhs' => 'qtk_local_qtk_codigo_cliente_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_codigo_cliente_1qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'qtk_local_qtk_cupon_juego_1' => 
  array (
    'id' => '282913e5-48fb-b928-37ec-5d1eb5d9b591',
    'relationship_name' => 'qtk_local_qtk_cupon_juego_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cupon_juego',
    'rhs_table' => 'qtk_cupon_juego',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_cupon_juego_1_c',
    'join_key_lhs' => 'qtk_local_qtk_cupon_juego_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_cupon_juego_1qtk_cupon_juego_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_local_qtk_afiliacion_1' => 
  array (
    'id' => '2f99a3a2-b8a8-5aed-9383-5d1eb5a196f5',
    'relationship_name' => 'qtk_local_qtk_afiliacion_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_afiliacion',
    'rhs_table' => 'qtk_afiliacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_afiliacion_1_c',
    'join_key_lhs' => 'qtk_local_qtk_afiliacion_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_afiliacion_1qtk_afiliacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_local_qtk_acumulacion_1' => 
  array (
    'id' => '34542af6-c58f-c6c8-62ff-5d1eb576ef27',
    'relationship_name' => 'qtk_local_qtk_acumulacion_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_acumulacion',
    'rhs_table' => 'qtk_acumulacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_acumulacion_1_c',
    'join_key_lhs' => 'qtk_local_qtk_acumulacion_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_acumulacion_1qtk_acumulacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_local_1' => 
  array (
    'id' => '3ef8168e-4e46-6656-0637-5d1eb5f53b2e',
    'relationship_name' => 'qtk_negocio_qtk_local_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_local_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_local_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_local_1qtk_local_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_local_qtk_redencion_1' => 
  array (
    'id' => '41e683d8-a255-d891-e118-5d1eb5eae39f',
    'relationship_name' => 'qtk_local_qtk_redencion_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_redencion',
    'rhs_table' => 'qtk_redencion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_redencion_1_c',
    'join_key_lhs' => 'qtk_local_qtk_redencion_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_redencion_1qtk_redencion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_local_qtk_codigo_cliente_2' => 
  array (
    'id' => '50518b74-3aa2-4874-c7b7-5d1eb514c7d2',
    'relationship_name' => 'qtk_local_qtk_codigo_cliente_2',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_codigo_cliente_2_c',
    'join_key_lhs' => 'qtk_local_qtk_codigo_cliente_2qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_codigo_cliente_2qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_local_modified_user' => 
  array (
    'id' => '6d204db4-6725-4b57-59b2-5d1eb5c7df0b',
    'relationship_name' => 'qtk_local_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_local_created_by' => 
  array (
    'id' => '6e8ecac6-d18e-39fe-3e91-5d1eb5a977ab',
    'relationship_name' => 'qtk_local_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_local_assigned_user' => 
  array (
    'id' => '7057ad5b-83cb-7590-1933-5d1eb56405b3',
    'relationship_name' => 'qtk_local_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_qtk_local' => 
  array (
    'id' => '71ea311f-3745-7dbf-5a3e-5d1eb5357659',
    'relationship_name' => 'securitygroups_qtk_local',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'qtk_local',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_local_qtk_reverso_1' => 
  array (
    'rhs_label' => 'Reversos',
    'lhs_label' => 'Local',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'qtk_local',
    'rhs_module' => 'qtk_reverso',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'qtk_local_qtk_reverso_1',
  ),
);