<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'qtk',
  'author' => 'Geovanny Santana',
  'description' => 'Módulos para Vinco 360',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Vinco',
  'published_date' => '2019-06-22 03:53:14',
  'type' => 'module',
  'version' => 1561175594,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Vinco',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'qtk_campania',
      'class' => 'qtk_campania',
      'path' => 'modules/qtk_campania/qtk_campania.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'qtk_tipo_evento',
      'class' => 'qtk_tipo_evento',
      'path' => 'modules/qtk_tipo_evento/qtk_tipo_evento.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'qtk_premio',
      'class' => 'qtk_premio',
      'path' => 'modules/qtk_premio/qtk_premio.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'qtk_cliente_negocio',
      'class' => 'qtk_cliente_negocio',
      'path' => 'modules/qtk_cliente_negocio/qtk_cliente_negocio.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'qtk_reverso',
      'class' => 'qtk_reverso',
      'path' => 'modules/qtk_reverso/qtk_reverso.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'qtk_log_notificacion_cliente',
      'class' => 'qtk_log_notificacion_cliente',
      'path' => 'modules/qtk_log_notificacion_cliente/qtk_log_notificacion_cliente.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'qtk_partida',
      'class' => 'qtk_partida',
      'path' => 'modules/qtk_partida/qtk_partida.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'qtk_cuenta',
      'class' => 'qtk_cuenta',
      'path' => 'modules/qtk_cuenta/qtk_cuenta.php',
      'tab' => true,
    ),
    8 => 
    array (
      'module' => 'qtk_acumulacion',
      'class' => 'qtk_acumulacion',
      'path' => 'modules/qtk_acumulacion/qtk_acumulacion.php',
      'tab' => true,
    ),
    9 => 
    array (
      'module' => 'qtk_codigo_cliente',
      'class' => 'qtk_codigo_cliente',
      'path' => 'modules/qtk_codigo_cliente/qtk_codigo_cliente.php',
      'tab' => true,
    ),
    10 => 
    array (
      'module' => 'qtk_cliente_negocio_calificacion',
      'class' => 'qtk_cliente_negocio_calificacion',
      'path' => 'modules/qtk_cliente_negocio_calificacion/qtk_cliente_negocio_calificacion.php',
      'tab' => true,
    ),
    11 => 
    array (
      'module' => 'qtk_afiliacion',
      'class' => 'qtk_afiliacion',
      'path' => 'modules/qtk_afiliacion/qtk_afiliacion.php',
      'tab' => true,
    ),
    12 => 
    array (
      'module' => 'qtk_local',
      'class' => 'qtk_local',
      'path' => 'modules/qtk_local/qtk_local.php',
      'tab' => true,
    ),
    13 => 
    array (
      'module' => 'qtk_redencion',
      'class' => 'qtk_redencion',
      'path' => 'modules/qtk_redencion/qtk_redencion.php',
      'tab' => true,
    ),
    14 => 
    array (
      'module' => 'qtk_negocio',
      'class' => 'qtk_negocio',
      'path' => 'modules/qtk_negocio/qtk_negocio.php',
      'tab' => true,
    ),
    15 => 
    array (
      'module' => 'qtk_cupon_juego',
      'class' => 'qtk_cupon_juego',
      'path' => 'modules/qtk_cupon_juego/qtk_cupon_juego.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_campania',
      'to' => 'modules/qtk_campania',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_tipo_evento',
      'to' => 'modules/qtk_tipo_evento',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_premio',
      'to' => 'modules/qtk_premio',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_cliente_negocio',
      'to' => 'modules/qtk_cliente_negocio',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_reverso',
      'to' => 'modules/qtk_reverso',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_log_notificacion_cliente',
      'to' => 'modules/qtk_log_notificacion_cliente',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_partida',
      'to' => 'modules/qtk_partida',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_cuenta',
      'to' => 'modules/qtk_cuenta',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_acumulacion',
      'to' => 'modules/qtk_acumulacion',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_codigo_cliente',
      'to' => 'modules/qtk_codigo_cliente',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_cliente_negocio_calificacion',
      'to' => 'modules/qtk_cliente_negocio_calificacion',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_afiliacion',
      'to' => 'modules/qtk_afiliacion',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_local',
      'to' => 'modules/qtk_local',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_redencion',
      'to' => 'modules/qtk_redencion',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_negocio',
      'to' => 'modules/qtk_negocio',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/qtk_cupon_juego',
      'to' => 'modules/qtk_cupon_juego',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);