<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'qtk_local_qtk_codigo_cliente_1' => 
  array (
    'id' => '8f322cc7-3c86-4646-c7e1-5d0dc40768f1',
    'relationship_name' => 'qtk_local_qtk_codigo_cliente_1',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_codigo_cliente_1_c',
    'join_key_lhs' => 'qtk_local_qtk_codigo_cliente_1qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_codigo_cliente_1qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'contacts_qtk_codigo_cliente_1' => 
  array (
    'id' => '9073a43e-87ee-4e4d-c2dc-5d0dc4bca599',
    'relationship_name' => 'contacts_qtk_codigo_cliente_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'contacts_qtk_codigo_cliente_1_c',
    'join_key_lhs' => 'contacts_qtk_codigo_cliente_1contacts_ida',
    'join_key_rhs' => 'contacts_qtk_codigo_cliente_1qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_codigo_cliente_2' => 
  array (
    'id' => '9f5f721a-fdcb-9743-c0c8-5d0dc4b255c6',
    'relationship_name' => 'qtk_negocio_qtk_codigo_cliente_2',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_codigo_cliente_2_c',
    'join_key_lhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_codigo_cliente_1' => 
  array (
    'id' => 'a590916e-f047-518e-e50a-5d0dc4f66d4f',
    'relationship_name' => 'qtk_negocio_qtk_codigo_cliente_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_codigo_cliente_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_codigo_cliente_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_codigo_cliente_1qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'qtk_local_qtk_codigo_cliente_2' => 
  array (
    'id' => 'b81c98f2-f20b-0c9d-b9ca-5d0dc45be827',
    'relationship_name' => 'qtk_local_qtk_codigo_cliente_2',
    'lhs_module' => 'qtk_local',
    'lhs_table' => 'qtk_local',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_local_qtk_codigo_cliente_2_c',
    'join_key_lhs' => 'qtk_local_qtk_codigo_cliente_2qtk_local_ida',
    'join_key_rhs' => 'qtk_local_qtk_codigo_cliente_2qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_codigo_cliente_qtk_acumulacion_1' => 
  array (
    'id' => 'bba0af1b-e102-87c6-fee9-5d0dc41db8a8',
    'relationship_name' => 'qtk_codigo_cliente_qtk_acumulacion_1',
    'lhs_module' => 'qtk_codigo_cliente',
    'lhs_table' => 'qtk_codigo_cliente',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_acumulacion',
    'rhs_table' => 'qtk_acumulacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_codigo_cliente_qtk_acumulacion_1_c',
    'join_key_lhs' => 'qtk_codigo_cliente_qtk_acumulacion_1qtk_codigo_cliente_ida',
    'join_key_rhs' => 'qtk_codigo_cliente_qtk_acumulacion_1qtk_acumulacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_codigo_cliente_modified_user' => 
  array (
    'id' => 'ce7156cb-667d-8abf-7dcc-5d0dc482da59',
    'relationship_name' => 'qtk_codigo_cliente_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_codigo_cliente_created_by' => 
  array (
    'id' => 'cfcfa41b-5306-6a91-0a25-5d0dc429638e',
    'relationship_name' => 'qtk_codigo_cliente_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_codigo_cliente_assigned_user' => 
  array (
    'id' => 'd14f748f-a53e-3f44-5573-5d0dc4814269',
    'relationship_name' => 'qtk_codigo_cliente_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_qtk_codigo_cliente' => 
  array (
    'id' => 'd28dac25-b1a5-ee31-963f-5d0dc4d45d6e',
    'relationship_name' => 'securitygroups_qtk_codigo_cliente',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'qtk_codigo_cliente',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_codigo_cliente_qtk_afiliacion_1' => 
  array (
    'rhs_label' => 'Vincard',
    'lhs_label' => 'Vincard',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'qtk_codigo_cliente',
    'rhs_module' => 'qtk_afiliacion',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'qtk_codigo_cliente_qtk_afiliacion_1',
  ),
);