<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'qtk_negocio_qtk_redencion_1' => 
  array (
    'id' => '5bd51f00-91df-4372-0501-5d41236755ae',
    'relationship_name' => 'qtk_negocio_qtk_redencion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_redencion',
    'rhs_table' => 'qtk_redencion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_redencion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_redencion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_redencion_1qtk_redencion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_reverso_1' => 
  array (
    'id' => '6102a2d6-aff6-2f1b-ca16-5d41230ae22b',
    'relationship_name' => 'qtk_negocio_qtk_reverso_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_reverso',
    'rhs_table' => 'qtk_reverso',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_reverso_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_reverso_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_reverso_1qtk_reverso_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_codigo_cliente_2' => 
  array (
    'id' => '6390bce0-5dc8-6965-2b36-5d4123d696dc',
    'relationship_name' => 'qtk_negocio_qtk_codigo_cliente_2',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_codigo_cliente_2_c',
    'join_key_lhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_campania_1' => 
  array (
    'id' => '6628d1f7-4605-14f5-bff8-5d4123a5e957',
    'relationship_name' => 'qtk_negocio_qtk_campania_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_campania',
    'rhs_table' => 'qtk_campania',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_campania_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_campania_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_campania_1qtk_campania_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_local_1' => 
  array (
    'id' => '68e7ca7f-3d05-ef5c-84ab-5d4123cdc2c9',
    'relationship_name' => 'qtk_negocio_qtk_local_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_local_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_local_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_local_1qtk_local_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cliente_negocio_calificacion_1' => 
  array (
    'id' => '6e06f823-1853-d87c-e607-5d4123c7e8b9',
    'relationship_name' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cliente_negocio_calificacion',
    'rhs_table' => 'qtk_cliente_negocio_calificacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocifabeicacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_afiliacion_1' => 
  array (
    'id' => '732678e7-6bde-9a1c-1c4f-5d41231022c1',
    'relationship_name' => 'qtk_negocio_qtk_afiliacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_afiliacion',
    'rhs_table' => 'qtk_afiliacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_afiliacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_afiliacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_afiliacion_1qtk_afiliacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cupon_juego_1' => 
  array (
    'id' => '75b8aa73-8766-1fd6-302a-5d41232b1182',
    'relationship_name' => 'qtk_negocio_qtk_cupon_juego_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cupon_juego',
    'rhs_table' => 'qtk_cupon_juego',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cupon_juego_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cupon_juego_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cupon_juego_1qtk_cupon_juego_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_log_notificacion_cliente_1' => 
  array (
    'id' => '7ae2b571-c8a3-643e-f7b7-5d4123271963',
    'relationship_name' => 'qtk_negocio_qtk_log_notificacion_cliente_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_log_notificacion_cliente',
    'rhs_table' => 'qtk_log_notificacion_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_log_notificacion_cliente_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_log_notificacion_cliente_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negoci8ab9cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_modified_user' => 
  array (
    'id' => '8d0a8bc2-6de6-f931-de43-5d41232bf50f',
    'relationship_name' => 'qtk_negocio_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_created_by' => 
  array (
    'id' => '8ee825c3-871f-ce2e-7cd3-5d412349757f',
    'relationship_name' => 'qtk_negocio_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_assigned_user' => 
  array (
    'id' => '917d1659-283f-a765-433a-5d4123c1c648',
    'relationship_name' => 'qtk_negocio_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_qtk_negocio' => 
  array (
    'id' => '94137616-49f8-367d-8a65-5d4123e90d81',
    'relationship_name' => 'securitygroups_qtk_negocio',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'qtk_negocio',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_qtk_cliente_negocio_1' => 
  array (
    'id' => '9a0aacbb-d941-4978-6cf6-5d41234f86d6',
    'relationship_name' => 'qtk_negocio_qtk_cliente_negocio_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cliente_negocio',
    'rhs_table' => 'qtk_cliente_negocio',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cliente_negocio_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cliente_negocio_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cliente_negocio_1qtk_cliente_negocio_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_premio_1' => 
  array (
    'id' => 'a43ea493-4df2-ff00-9160-5d41236f55f9',
    'relationship_name' => 'qtk_negocio_qtk_premio_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_premio',
    'rhs_table' => 'qtk_premio',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_premio_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_premio_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_premio_1qtk_premio_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_acumulacion_1' => 
  array (
    'id' => 'a9871c4c-b6ba-a102-cafa-5d4123a3be96',
    'relationship_name' => 'qtk_negocio_qtk_acumulacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_acumulacion',
    'rhs_table' => 'qtk_acumulacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_acumulacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_acumulacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_acumulacion_1qtk_acumulacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cuenta_1' => 
  array (
    'id' => 'aed6c43b-87ca-71f2-5293-5d4123631a5e',
    'relationship_name' => 'qtk_negocio_qtk_cuenta_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cuenta',
    'rhs_table' => 'qtk_cuenta',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cuenta_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cuenta_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cuenta_1qtk_cuenta_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_securitygroups_1' => 
  array (
    'rhs_label' => 'Gestión de Seguridad',
    'lhs_label' => 'Negocios',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'admin',
    'lhs_module' => 'qtk_negocio',
    'rhs_module' => 'SecurityGroups',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'qtk_negocio_securitygroups_1',
  ),
);