<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'qtk_negocio_modified_user' => 
  array (
    'id' => '507e802f-cdfe-62cd-fdd6-5d1eb5acd7a0',
    'relationship_name' => 'qtk_negocio_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_created_by' => 
  array (
    'id' => '527eaa44-5bdc-45b6-5e63-5d1eb572e01c',
    'relationship_name' => 'qtk_negocio_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_assigned_user' => 
  array (
    'id' => '5457f145-553c-cb7d-0bef-5d1eb5969a64',
    'relationship_name' => 'qtk_negocio_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_qtk_negocio' => 
  array (
    'id' => '557764fd-0310-82a3-8167-5d1eb52325c1',
    'relationship_name' => 'securitygroups_qtk_negocio',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_negocio',
    'rhs_table' => 'qtk_negocio',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'qtk_negocio',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_qtk_premio_1' => 
  array (
    'id' => 'c209f46b-0459-1f14-3e0d-5d1eb5ad3fc1',
    'relationship_name' => 'qtk_negocio_qtk_premio_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_premio',
    'rhs_table' => 'qtk_premio',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_premio_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_premio_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_premio_1qtk_premio_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cliente_negocio_1' => 
  array (
    'id' => 'c5c6c1b6-ab64-fb19-1ce2-5d1eb530c9b0',
    'relationship_name' => 'qtk_negocio_qtk_cliente_negocio_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cliente_negocio',
    'rhs_table' => 'qtk_cliente_negocio',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cliente_negocio_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cliente_negocio_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cliente_negocio_1qtk_cliente_negocio_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_log_notificacion_cliente_1' => 
  array (
    'id' => 'c6f145fd-791b-9a18-b4d0-5d1eb5bd2629',
    'relationship_name' => 'qtk_negocio_qtk_log_notificacion_cliente_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_log_notificacion_cliente',
    'rhs_table' => 'qtk_log_notificacion_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_log_notificacion_cliente_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_log_notificacion_cliente_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negoci8ab9cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cupon_juego_1' => 
  array (
    'id' => 'ca932584-e9db-5ed6-482b-5d1eb57d1288',
    'relationship_name' => 'qtk_negocio_qtk_cupon_juego_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cupon_juego',
    'rhs_table' => 'qtk_cupon_juego',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cupon_juego_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cupon_juego_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cupon_juego_1qtk_cupon_juego_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_afiliacion_1' => 
  array (
    'id' => 'cbde7627-0f9b-2798-55fe-5d1eb59f295a',
    'relationship_name' => 'qtk_negocio_qtk_afiliacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_afiliacion',
    'rhs_table' => 'qtk_afiliacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_afiliacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_afiliacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_afiliacion_1qtk_afiliacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_campania_1' => 
  array (
    'id' => 'ce990786-7e44-1888-3815-5d1eb5b67426',
    'relationship_name' => 'qtk_negocio_qtk_campania_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_campania',
    'rhs_table' => 'qtk_campania',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_campania_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_campania_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_campania_1qtk_campania_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_codigo_cliente_2' => 
  array (
    'id' => 'cfcd534f-2ade-a3ac-4226-5d1eb5a5bdce',
    'relationship_name' => 'qtk_negocio_qtk_codigo_cliente_2',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_codigo_cliente_2_c',
    'join_key_lhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_codigo_cliente_2qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_codigo_cliente_1' => 
  array (
    'id' => 'd6083efe-6f04-b48c-1fa8-5d1eb50fd408',
    'relationship_name' => 'qtk_negocio_qtk_codigo_cliente_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_codigo_cliente',
    'rhs_table' => 'qtk_codigo_cliente',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_codigo_cliente_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_codigo_cliente_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_codigo_cliente_1qtk_codigo_cliente_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'qtk_negocio_qtk_cliente_negocio_calificacion_1' => 
  array (
    'id' => 'd7475ced-3a39-83cc-912a-5d1eb57227a4',
    'relationship_name' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cliente_negocio_calificacion',
    'rhs_table' => 'qtk_cliente_negocio_calificacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cliente_negocio_calificacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocifabeicacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_local_1' => 
  array (
    'id' => 'd9ad6043-916d-d214-e629-5d1eb5ff3665',
    'relationship_name' => 'qtk_negocio_qtk_local_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_local',
    'rhs_table' => 'qtk_local',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_local_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_local_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_local_1qtk_local_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_acumulacion_1' => 
  array (
    'id' => 'db03edef-5df4-e0c6-06a7-5d1eb58c0c58',
    'relationship_name' => 'qtk_negocio_qtk_acumulacion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_acumulacion',
    'rhs_table' => 'qtk_acumulacion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_acumulacion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_acumulacion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_acumulacion_1qtk_acumulacion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_cuenta_1' => 
  array (
    'id' => 'e09ad116-2f8e-3e86-aa27-5d1eb5fb8158',
    'relationship_name' => 'qtk_negocio_qtk_cuenta_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_cuenta',
    'rhs_table' => 'qtk_cuenta',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_cuenta_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_cuenta_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_cuenta_1qtk_cuenta_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_redencion_1' => 
  array (
    'id' => 'e5d2778e-460b-8b13-7a13-5d1eb529a7ef',
    'relationship_name' => 'qtk_negocio_qtk_redencion_1',
    'lhs_module' => 'qtk_negocio',
    'lhs_table' => 'qtk_negocio',
    'lhs_key' => 'id',
    'rhs_module' => 'qtk_redencion',
    'rhs_table' => 'qtk_redencion',
    'rhs_key' => 'id',
    'join_table' => 'qtk_negocio_qtk_redencion_1_c',
    'join_key_lhs' => 'qtk_negocio_qtk_redencion_1qtk_negocio_ida',
    'join_key_rhs' => 'qtk_negocio_qtk_redencion_1qtk_redencion_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'qtk_negocio_qtk_reverso_1' => 
  array (
    'rhs_label' => 'Reversos',
    'lhs_label' => 'Negocio',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'qtk_negocio',
    'rhs_module' => 'qtk_reverso',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'qtk_negocio_qtk_reverso_1',
  ),
);